### ISSUE TITLE
Integrate LiipCacheControlBundle

### ISSUE THREAD

**Issue by vivienlacourba** [vivienlacourba/trac-w3caccountsbundle#70]
**Reported by denis on 13 Jul 2012 15:47 UTC**

```
# config.yml
liip_cache_control:
    rules:  
        # Make sure login and logout are not cached at all
        -       
            path: ^/(login|login_check|logout)
            controls:
                private: true
                max_age: 0
        # Cache the homepage for 10 minutes 
        -       
            path: ^/$
            vary: Cookie
            controls:
                public: true
                max_age: 600
        # Cache every other page for 1 hour
        -       
            path: ^/
            vary: Cookie
            controls:
                public: true
                max_age: 3600                        
```
